name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-24
    with:
      maven-single-run: false
      jdk-matrix: '[ "17", "21" ]'
      maven-test: './mvnw clean install -e -B -V'
